version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database
    volumes:
      - concourse-db-data:/database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    # DNS configuration to resolve external hosts
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # Database connection
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      
      # Web configuration
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: admin:admin
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin
      
      # Garden-specific DNS configuration options
      CONCOURSE_GARDEN_DNS_SERVER: "8.8.8.8,8.8.4.4"
      
      # The default network pool from ps output (matches what you're running)
      CONCOURSE_GARDEN_NETWORK_POOL: "10.80.0.0/16"
      
      # These improve container management 
      CONCOURSE_GARDEN_MAX_CONTAINERS: "250"

      # Debugging options - uncomment if needed
      # CONCOURSE_GARDEN_DEBUG_BIND_IP: "127.0.0.1"
      # CONCOURSE_GARDEN_DEBUG_BIND_PORT: "17013"
      
      # Uncomment if behind a proxy
      # HTTP_PROXY: "http://your-proxy:port"
      # HTTPS_PROXY: "http://your-proxy:port"
      # NO_PROXY: "localhost,127.0.0.1,concourse-db"

volumes:
  concourse-db-data:
    driver: local
